### ISSUE TITLE
Forklaring med windows 10

### ISSUE THREAD

**Issue by ArgTang** [hioa-cs/webprosjekt#6]
Map network drive ikon er ikke på samme sed i w10 som i w7\8

**Comment by jthanto** [comment]
Usikker på om denne er aktiv fremdeles jeg.
Ser jo litt ut som om den ikke er det ut fra beskrivelsen.
"Ressurser i forbindelse med kurset Webprosjekt, høsten 2013 ved HiOA. Alle henvendelser fra studenter i dette kurset skal sendes til webprosjekt@cs.hioa.no."

**Comment by fwsGonzo** [comment]
Indeed

**Comment by jthanto** [comment]
Prøv et Google søk med map network drive win10.  It might just work. Ellers bør også skolen ha egne resurser på dette på sine nettsteder =]

**Comment by ArgTang** [comment]
Ok, den er linket inn fra webprosjekt på fronter i år. Skal si ifra til foreleser, får se hva de gjør med den :)

**Comment by jthanto** [comment]
Jeg vil anta at dersom det ikke er Alfred Bratterud som er foreleser i faget, vil ikke denne bli oppdatert. Jeg kan jo selvfølgelig ta feil. Lykke til! :)

**Comment by A-Lee** [comment]
Alfred er ikke foreleser i år nei. Må jeg sende melding til  webprosjekt@cs.hioa.no<mailto:webprosjekt@cs.hioa.no> for å få den åpnet? Innleveringen er imorgen kl 23 så det haster veldig


________________________________

**Comment by jthanto** [comment]
Dudes and dudettes, snakk med foreleseren deres, best bet for å få den infoen dere trenger. Dere vil etter all sannsynlighet ikke få den informasjonen dere trenger her, desverre. Foreleser eller den personen som har administrativt ansvar for kurset dere tar bør kunne svare på det dere lurer på.

**Comment by Chr1stian** [comment]
Får alle disse mailene fordi jeg hadde dette faget for 2 år siden, så slutt!!


23. sep. 2015 kl. 22:49 skrev Jan Thomas Hanto <notifications@github.com>:

**Comment by jthanto** [comment]
Alle har vært nye i studiene sine en gang, og bør få muligheten til å få hjelp. Tipser deg i samme slengen om unwatch for dette repoet. Tror det kommer til å fikse problemet ditt. Dette problemet er heller ikke relatert til opprinnelig problem, så har du videre problemer med dette foreslår jeg at du lager deg ett eget issue.

Mvh.
Avdelingen for medmenneskelighet.

**Comment by alfred-bratterud** [comment]
Hehe, 

Veldig bra at vi har en avdeling for medmenneskelighet :-)
